### ISSUE TITLE
The project selector needs to be wider to fill the full name of the projects

### ISSUE THREAD

**Issue by marianamarasoiu** [AfricasVoices/nook_watcher#11]
The COVID19-KE-URBAN project is about as long as we're likely to get, so it should fit that and maybe a little bit more.

**Comment by ktkization** [comment]
[PL](https://github.com/AfricasVoices/nook_watcher/pull/14) for this feature

**Comment by marianamarasoiu** [comment]
Thanks, closing this issue as it's fixed now!
