### ISSUE TITLE
UI widget selector to choose the timeline width

### ISSUE THREAD

**Issue by marianamarasoiu** [AfricasVoices/nook_watcher#13]
At the moment we display data for all time. For longer running pipelines, we're starting to see the need to be able to look at only more recent times only.

A good set of intervals to have to choose from would be:
- last day
- last 8 days
- last 15 days
- last month
- all time

**Comment by ktkization** [comment]
Assigned this to myself

**Comment by ktkization** [comment]
[PL](https://github.com/AfricasVoices/nook_watcher/pull/15) for this feature

**Comment by marianamarasoiu** [comment]
@ktkization I think this is done now, so we can close it
