### ISSUE TITLE
Move the date range filter into the header bar

### ISSUE THREAD

**Issue by marianamarasoiu** [AfricasVoices/nook_watcher#19]

**Comment by ktkization** [comment]
I have a question regarding this. What if we end up with multiple filters. Won't the header get too crowded?

**Comment by marianamarasoiu** [comment]
that's a good point, but I think for a monitoring tool it's ok for the header bar to be full of filters. If we do end up with so many filters that they no longer fit on the header properly, we might need to think about a better way to lay them out, but at the moment the concern is that we should keep the main window only for the timeline charts and key values.

**Comment by ktkization** [comment]
alright

**Comment by ktkization** [comment]
[PL](https://github.com/AfricasVoices/nook_watcher/pull/25) for change

**Comment by marianamarasoiu** [comment]
@ktkization thanks for fixing this!
