### ISSUE TITLE
System metrics (CPU/RAM etc) charts don't set the time period correctly sometimes

### ISSUE THREAD

**Issue by marianamarasoiu** [AfricasVoices/nook_watcher#92]
This only happens when decreasing the time period shown. Example:
- load nook-watcher with time period 1 day -> charts show correct time period (yesterday -> today)
- change time period to 8 days -> charts show correct time period (8 days ago -> today)
- change time period back to 1 day -> charts remain showing the previous time period (8 days ago -> today)

**Comment by ktkization** [comment]
@marianamarasoiu I might have fixed this while doing #93 / #66
